spring:
 profiles:
  active:
  - eureka2001
---
server:
  port: 2001
  context-path: /
eureka:
  instance:
    hostname: eureka2001.p2p.com
  client:
    register-with-eureka: false
    fetch-registry: false

    service-url:
      defaultZone: http://eureka2002.p2p.com:2002/eureka/,http://eureka2003.p2p.com:2003/eureka/
spring:
  profiles: eureka2001
---
server:
  port: 2002
  context-path: /
eureka:
  instance:
    hostname: eureka2002.p2p.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka2001.p2p.com:2001/eureka/,http://eureka2003.p2p.com:2003/eureka/
spring:
  profiles: eureka2002
---
server:
  port: 2003
  context-path: /
eureka:
  instance:
    hostname: eureka2003.p2p.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka2001.p2p.com:2001/eureka/,http://eureka2002.p2p.com:2002/eureka/
spring:
  profiles: eureka2003
